openapi: "3.0.0"
info:
  title: Dynamic client registration
  description: |
    Dynamic client registration is described in https://tools.ietf.org/html/rfc7591. This specification is the yaml file describing the endpoint.
  version: v1
servers: 
  - url: https://www.vorstdev.com/oauth2
    description: OAUTH2 server
tags:
  - name: V1Register
paths:
  /v1/register:
    post:
      tags: 
        - V1Register
      operationId: "registerClient"
      summary: "Register a client"
      requestBody:
        description: todo
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ClientMetaData"
      responses:
        302:
          description : "Success"
          headers:
            Location:
              description: Redirect to given redirect_url or a default, for example https://client.example.com/cb?code=SplxlOBeZQQYbYS6WxSbIA&state=xyz"
              schema:
                type: "string"
components:
  schemas:
    ClientMetaData:
      type: "object"
      properties:
        redirect_uris:
          type: array
          items:
            type: string
            format: uri
            example: "https://myapp.vorstdev.com/profile"
        token_endpoint_auth_method:
          $ref: '#/components/schemas/TokenEndpointAuthMethods'
        grant_types:
          $ref: '#/components/schemas/GrantTypes'
        response_types:
          $ref: '#/components/schemas/ResponseTypes'
        client_name:
          type: string
          pattern: ^[a-zA-Z0-9 .-]+$]]
          example: App1-client
          minLength: 5
          maxLength: 50
        client_uri:
          type: string
          format: uri
          example: "https://myapp.vorstdev.com/client"
        logo_uri:
          type: string
          format: uri
          example: "https://myapp.vorstdev.com/logo"
        scope:
          type: string
          pattern: ^(?:\s+[A-Za-z0-9]+)+\s+$
          example: A1:R1:Read A2:R2:Read
        contacts:
          type: array
          items:
            type: string
            format: email
        tos_uri:
          type: string
          format: uri
          example: "https://myapp.vorstdev.com/terms-of-services"
        policy_uri:
          type: string
          format: uri
          example: "https://myapp.vorstdev.com/policy"
        jwks_uri:
          type: string
          format: uri
          example: "https://myapp.vorstdev.com/jwks"
        jwks:
          type: string
          example: "jwks TODO"
        software_id:
          type: string
          format: uuid
        software_version:
          type: string
          example: "TODO"
    ResponseTypes:
      type: string
      enum:
        - code
        - token
    GrantTypes:
      type: string
      enum:
        - authorization_code
        - implicit
        - password
        - client_credentials
        - refresh_token
        - urn:ietf:params:oauth:grant-type:jwt-bearer
        - urn:ietf:params:oauth:grant-type:saml2-bearer
    TokenEndpointAuthMethods:
      type: string
      enum:
        - none
        - client_secret_post
        - client_secret_basic
           
